[package]
name = "mojaloop-cli"
version = "0.1.0"
authors = ["msk- <mattkingston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
tokio = { version = "1.6.1", features = ["full"] }
tokio-util = "0.6"
futures = "0.3.15"
futures-util = "0.3.15"
mojaloop-api = { path = "/home/msk/projects/github.com/msk-/mojaloop-api/" }
thiserror = "1.0"
httparse = "1.4"
serde = "1.0"
serde_json = "1.0"
# Per the advice here: https://github.com/clux/kube-rs#rustls
kube = { git = "https://github.com/kazk/kube-rs", rev = "e1b02c57d9ebd5bbf0d93b244a7be4b7438d3b66", default-features = false, features = ["client", "rustls-tls", "ws"] }
kube-runtime = { version = "0.56.0" }
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
