[package]
name = "mojaloop-cli"
version = "0.7.0"
authors = ["msk- <mattkingston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
# Pinning clap to avoid compile issues with 3.0.0-beta.4.
clap = "=3.0.0-beta.2"
clap_derive = "=3.0.0-beta.2"
cli-table = "0.4"
hyper = "0.14"
http = "0.2.4" # probably needs to be the same as our version of hyper
tokio = { version = "1.6.1", features = ["full"] }
tokio-util = "0.6"
futures = "0.3.15"
futures-util = "0.3.15"
mojaloop-api = { git = "https://github.com/partiallyordered/mojaloop-api", rev = "ea15750b6ddbd1e7902731ea932186e204e8ecd3", features = ["hyper"] }
# mojaloop-api = { path = "/home/msk/projects/github.com/msk-/mojaloop-api/", features = ["hyper"] }
fspiox-api = { git = "https://github.com/partiallyordered/fspiox-api", rev = "71077473df01cbab245fe334690848dbba998f23", features = ["fsp_http"] }
# fspiox-api = { path = "/home/msk/projects/github.com/msk-/fspiox-api/" ,features = ["fsp_http"] }
thiserror = "1.0"
httparse = "1.4"
serde = "1.0"
serde_json = "1.0"
# Note: we can't use rustls because of this issue: https://github.com/clux/kube-rs/issues/153
kube = { git = "https://github.com/kazk/kube-rs", rev = "e1b02c57d9ebd5bbf0d93b244a7be4b7438d3b66", features = ["ws"] }
kube-runtime = { version = "0.56.0" }
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
openssl = { version = "0.10", features = ["vendored"] }
url = "2"
strum = "0.21"
strum_macros = "0.21"
voodoo-doll = { git = "https://github.com/partiallyordered/voodoo-doll", rev = "07b34f2b7b39592b92d14b72148def051d4e2cf1" }
# voodoo-doll = { path = "/home/msk/projects/github.com/msk-/voodoo-doll/" }
tokio-tungstenite = "0.14"
rust_decimal = "1"
