name: Publish to Github

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # TODO: delete the release if it fails? Or just hope to notice and do so manually?
  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
    - name: Create artifacts directory
      run: mkdir artifacts
    - name: Get the release version from the tag
      run: |
        # Apparently, this is the right way to get a tag name. Really?
        #
        # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
        echo "ML_CLI_VER=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.ML_CLI_VER }}
        body: ${{ env.ML_CLI_VER }}
        draft: false
        prerelease: false
    - name: Save release upload URL to artifact
      run: echo "${{ steps.release.outputs.upload_url }}" > artifacts/release-upload-url
    - name: Save version number to artifact
      run: echo "${{ env.ML_CLI_VER }}" > artifacts/release-version
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts

  publish-to-github:
    name: Publish to Github
    needs: ['create-release']
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build: [linux, macos]
        # build: [linux, arm, arm-v7, macos]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-musl
          cross: false
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          cross: false
        # - build: arm
        #   os: ubuntu-latest
        #   rust: stable
        #   target: arm-unknown-linux-gnueabihf
        #   cross: true
        # - build: arm-v7
        #   os: ubuntu-latest
        #   rust: stable
        #   target: armv7-unknown-linux-gnueabihf
        #   cross: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install correct toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        use-cross: ${{ matrix.cross }}
        override: true

    - name: Get release download URL
      uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: artifacts
    - name: Set release upload URL and release version
      shell: bash
      run: |
        release_upload_url="$(cat artifacts/release-upload-url)"
        echo "RELEASE_UPLOAD_URL=$release_upload_url" >> $GITHUB_ENV
        echo "release upload url: $RELEASE_UPLOAD_URL"
        release_version="$(cat artifacts/release-version)"
        echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
        echo "release version: $RELEASE_VERSION"

    - name: Install tools and libs
      shell: bash
      # TODO: Do this more like: https://github.com/lotabout/skim/tree/6df015987934bd63121be53d8659da0f44237dac/.github/workflows
      # In general probably study that other one a bit more. Also:
      # https://github.com/briansmith/webpki/blob/18cda8a5e32dfc2723930018853a984bd634e667/.github/workflows/ci.yml
      # in particular the test info on PRs: https://github.com/briansmith/webpki/pull/218#issuecomment-823721570
      run: |
        case $RUNNER_OS in
            Linux)
                sudo apt-get update
                sudo apt-get install -y -qq pkg-config libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev musl-tools
                ;;
            macOS)
                brew install openssl@1.1
                ;;
        esac

    - name: build
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.cross }}
        command: build
        args: --release --target ${{ matrix.target }}
    - name: Package Artifacts
      run: |
        src=$(pwd)
        stage=

        case $RUNNER_OS in
            Linux)
                stage=$(mktemp -d)
                ;;
            macOS)
                stage=$(mktemp -d -t tmp)
                ;;
        esac

        echo "src is: $src"
        echo "stage is: $stage"

        cp target/${{ matrix.target }}/release/mojaloop-cli $stage/
        cd $stage

        ASSET_NAME="mojaloop-cli-${{ env.RELEASE_VERSION }}-${{ matrix.target }}.tar.gz"
        ASSET_PATH="$src/$ASSET_NAME"
        echo "ASSET_NAME=$ASSET_NAME" >> $GITHUB_ENV
        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV

        tar czf $ASSET_PATH *

        cd $src
    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.RELEASE_UPLOAD_URL }}
        asset_path: ${{ env.ASSET_PATH }}
        asset_name: ${{ env.ASSET_NAME }}
        asset_content_type: application/octet-stream
