name: Enforce version change

on:
  push:
    branches:
    - '**'

jobs:
  version-change-test:
    name: Enforce version change
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get yj
      run: curl -L https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux > yj && chmod +x yj
    - name: Get branch Cargo version
      run: ./yj -tj < Cargo.toml | jq '.package.version' -r > versions
    - name: Get base branch Cargo version
      run: git show main:Cargo.toml | ./yj -tj | jq '.package.version' -r >> versions
    - name: Print versions
      run: cat versions
    - name: Assert there are two unique versions
      run: '[[ $(uniq < versions | wc -l) == 2 ]]'
