name: Enforce version change

on:
  push:
    # will run on every branch except main
    branches-ignore:
    - 'main'

jobs:
  version-change-test:
    name: Enforce version change
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: branch
    - name: Get yj
      run: curl -L https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux > yj && chmod +x yj
    - name: Get branch Cargo version
      run: ./yj -tj < branch/Cargo.toml | jq '.package.version' -r > versions
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        path: main
    - name: Get main branch Cargo version
      run: ./yj -tj < main/Cargo.toml | jq '.package.version' -r >> versions
    - name: Print versions
      run: cat versions
    - name: Assert there are two unique versions
      run: '[[ $(uniq < versions | wc -l) == 2 ]]'
